[package]
name = "yaebook-core"
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = "0.0.0"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
ureq = { workspace = true, features = ["gzip", "json", "native-tls"] }

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
ureq = { workspace = true, features = ["gzip", "json", "tls"] }

[lints]
workspace = true
